"""Theme Manager – Konstanten und Preset-Themes.

Jedes Theme definiert Farben unter 'modes.dark' und 'modes.light'.
Dadurch funktioniert der Auto/Dark/Light-Schalter im HA-Benutzerprofil
(Mein Konto → Erscheinungsbild → Design) korrekt.
"""

DOMAIN = "theme_manager"

# Gemeinsame Hilfsfunktion für den Aufbau einer Variablen-Map
def _vars(dark: dict, light: dict, shared: dict | None = None) -> dict:
    """Baut die variables-Struktur mit modes.dark / modes.light auf."""
    result: dict = {}
    if shared:
        result.update(shared)
    result["modes"] = {"dark": dark, "light": light}
    return result


# Strukturelle Variablen (keine Farben – gelten für beide Modi)
_SHARED_MODERN = {
    "ha-card-border-width": "0px",
    "ha-card-border-radius": "12px",
    "sidebar-menu-button-background-color": "transparent",
}
_SHARED_GITHUB = {
    "ha-card-border-width": "1px",
    "ha-card-border-radius": "8px",
    "sidebar-menu-button-background-color": "transparent",
}
_SHARED_PLAIN = {
    "ha-card-border-width": "0px",
    "ha-card-border-radius": "12px",
    "sidebar-menu-button-background-color": "transparent",
}


def _dark_vars(
    primary, accent, bg, bg2, card, text, text2,
    header_bg, header_text,
    sidebar_bg, sidebar_icon, sidebar_text,
    sidebar_sel_bg, sidebar_sel_icon, sidebar_sel_text,
    state_icon, error, success, warning, info, divider,
    table_row, table_row_alt, input_bg, input_text,
    mdc_surface, mat_bg, mat_bg2,
    badge_bg, badge_text, badge_red, badge_green, badge_blue, badge_yellow, badge_grey,
) -> dict:
    return {
        "primary-color": primary,
        "accent-color": accent,
        "primary-background-color": bg,
        "secondary-background-color": bg2,
        "card-background-color": card,
        "ha-card-background": card,
        "primary-text-color": text,
        "secondary-text-color": text2,
        "disabled-text-color": badge_grey,
        "text-primary-color": text,
        "app-header-background-color": header_bg,
        "app-header-text-color": header_text,
        "sidebar-background-color": sidebar_bg,
        "sidebar-icon-color": sidebar_icon,
        "sidebar-text-color": sidebar_text,
        "sidebar-selected-background-color": sidebar_sel_bg,
        "sidebar-selected-icon-color": sidebar_sel_icon,
        "sidebar-selected-text-color": sidebar_sel_text,
        "state-icon-color": state_icon,
        "error-color": error,
        "success-color": success,
        "warning-color": warning,
        "info-color": info,
        "divider-color": divider,
        "table-row-background-color": table_row,
        "table-row-alternative-background-color": table_row_alt,
        "input-fill-color": input_bg,
        "input-background-color": input_bg,
        "input-ink-color": input_text,
        "mdc-theme-surface": mdc_surface,
        "material-background-color": mat_bg,
        "material-secondary-background-color": mat_bg2,
        "label-badge-background-color": badge_bg,
        "label-badge-text-color": badge_text,
        "label-badge-red": badge_red,
        "label-badge-green": badge_green,
        "label-badge-blue": badge_blue,
        "label-badge-yellow": badge_yellow,
        "label-badge-grey": badge_grey,
    }


PRESET_THEMES = {
    # ------------------------------------------------------------------
    "modern_dark": {
        "display_name": "Modern Dark",
        "variables": _vars(
            shared=_SHARED_MODERN,
            dark=_dark_vars(
                primary="#1a73e8", accent="#03a9f4",
                bg="#121212", bg2="#1e1e1e", card="#1e1e1e",
                text="#e0e0e0", text2="#9e9e9e",
                header_bg="#1e1e1e", header_text="#e0e0e0",
                sidebar_bg="#1a1a2e", sidebar_icon="#9e9e9e", sidebar_text="#e0e0e0",
                sidebar_sel_bg="#0d0d1a", sidebar_sel_icon="#1a73e8", sidebar_sel_text="#1a73e8",
                state_icon="#4fc3f7",
                error="#f44336", success="#4caf50", warning="#ff9800", info="#2196f3",
                divider="#2c2c2c",
                table_row="#1e1e1e", table_row_alt="#242424",
                input_bg="#2c2c2c", input_text="#e0e0e0",
                mdc_surface="#1e1e1e", mat_bg="#121212", mat_bg2="#1e1e1e",
                badge_bg="#1e1e1e", badge_text="#e0e0e0",
                badge_red="#f44336", badge_green="#4caf50", badge_blue="#2196f3",
                badge_yellow="#ff9800", badge_grey="#616161",
            ),
            light=_dark_vars(
                primary="#1a73e8", accent="#0097a7",
                bg="#f5f5f5", bg2="#ffffff", card="#ffffff",
                text="#212121", text2="#757575",
                header_bg="#1a73e8", header_text="#ffffff",
                sidebar_bg="#ffffff", sidebar_icon="#757575", sidebar_text="#212121",
                sidebar_sel_bg="#e8f0fe", sidebar_sel_icon="#1a73e8", sidebar_sel_text="#1a73e8",
                state_icon="#0288d1",
                error="#d32f2f", success="#388e3c", warning="#f57c00", info="#1976d2",
                divider="#e0e0e0",
                table_row="#ffffff", table_row_alt="#f5f5f5",
                input_bg="#f0f0f0", input_text="#212121",
                mdc_surface="#ffffff", mat_bg="#f5f5f5", mat_bg2="#ffffff",
                badge_bg="#ffffff", badge_text="#212121",
                badge_red="#d32f2f", badge_green="#388e3c", badge_blue="#1976d2",
                badge_yellow="#f57c00", badge_grey="#9e9e9e",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "dracula": {
        "display_name": "Dracula",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#bd93f9", accent="#ff79c6",
                bg="#282a36", bg2="#21222c", card="#2a2b3d",
                text="#f8f8f2", text2="#6272a4",
                header_bg="#21222c", header_text="#f8f8f2",
                sidebar_bg="#1e1f29", sidebar_icon="#6272a4", sidebar_text="#f8f8f2",
                sidebar_sel_bg="#191a21", sidebar_sel_icon="#bd93f9", sidebar_sel_text="#bd93f9",
                state_icon="#ff79c6",
                error="#ff5555", success="#50fa7b", warning="#ffb86c", info="#8be9fd",
                divider="#44475a",
                table_row="#2a2b3d", table_row_alt="#33344a",
                input_bg="#44475a", input_text="#f8f8f2",
                mdc_surface="#2a2b3d", mat_bg="#282a36", mat_bg2="#21222c",
                badge_bg="#2a2b3d", badge_text="#f8f8f2",
                badge_red="#ff5555", badge_green="#50fa7b", badge_blue="#8be9fd",
                badge_yellow="#f1fa8c", badge_grey="#6272a4",
            ),
            light=_dark_vars(
                primary="#6272a4", accent="#bd93f9",
                bg="#f8f8f2", bg2="#f0f0e8", card="#ffffff",
                text="#282a36", text2="#6272a4",
                header_bg="#282a36", header_text="#f8f8f2",
                sidebar_bg="#f0f0e8", sidebar_icon="#6272a4", sidebar_text="#282a36",
                sidebar_sel_bg="#e4e4d8", sidebar_sel_icon="#bd93f9", sidebar_sel_text="#6272a4",
                state_icon="#bd93f9",
                error="#ff5555", success="#50fa7b", warning="#ffb86c", info="#8be9fd",
                divider="#d0d0c8",
                table_row="#ffffff", table_row_alt="#f5f5ec",
                input_bg="#f0f0e8", input_text="#282a36",
                mdc_surface="#ffffff", mat_bg="#f8f8f2", mat_bg2="#f0f0e8",
                badge_bg="#ffffff", badge_text="#282a36",
                badge_red="#ff5555", badge_green="#50fa7b", badge_blue="#8be9fd",
                badge_yellow="#f1fa8c", badge_grey="#6272a4",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "catppuccin_mocha": {
        "display_name": "Catppuccin Mocha",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#cba6f7", accent="#89b4fa",
                bg="#1e1e2e", bg2="#181825", card="#1e1e2e",
                text="#cdd6f4", text2="#a6adc8",
                header_bg="#181825", header_text="#cdd6f4",
                sidebar_bg="#181825", sidebar_icon="#a6adc8", sidebar_text="#cdd6f4",
                sidebar_sel_bg="#11111b", sidebar_sel_icon="#cba6f7", sidebar_sel_text="#cba6f7",
                state_icon="#f5c2e7",
                error="#f38ba8", success="#a6e3a1", warning="#fab387", info="#89b4fa",
                divider="#313244",
                table_row="#1e1e2e", table_row_alt="#262637",
                input_bg="#313244", input_text="#cdd6f4",
                mdc_surface="#1e1e2e", mat_bg="#1e1e2e", mat_bg2="#181825",
                badge_bg="#1e1e2e", badge_text="#cdd6f4",
                badge_red="#f38ba8", badge_green="#a6e3a1", badge_blue="#89b4fa",
                badge_yellow="#f9e2af", badge_grey="#6c7086",
            ),
            # Catppuccin Latte (offizielle Light-Variante)
            light=_dark_vars(
                primary="#8839ef", accent="#1e66f5",
                bg="#eff1f5", bg2="#e6e9ef", card="#ffffff",
                text="#4c4f69", text2="#5c5f77",
                header_bg="#8839ef", header_text="#eff1f5",
                sidebar_bg="#e6e9ef", sidebar_icon="#5c5f77", sidebar_text="#4c4f69",
                sidebar_sel_bg="#dce0e8", sidebar_sel_icon="#8839ef", sidebar_sel_text="#8839ef",
                state_icon="#04a5e5",
                error="#d20f39", success="#40a02b", warning="#df8e1d", info="#1e66f5",
                divider="#ccd0da",
                table_row="#ffffff", table_row_alt="#eff1f5",
                input_bg="#e6e9ef", input_text="#4c4f69",
                mdc_surface="#ffffff", mat_bg="#eff1f5", mat_bg2="#e6e9ef",
                badge_bg="#ffffff", badge_text="#4c4f69",
                badge_red="#d20f39", badge_green="#40a02b", badge_blue="#1e66f5",
                badge_yellow="#df8e1d", badge_grey="#9ca0b0",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "solarized_dark": {
        "display_name": "Solarized Dark",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#268bd2", accent="#b58900",
                bg="#002b36", bg2="#073642", card="#073642",
                text="#839496", text2="#586e75",
                header_bg="#002b36", header_text="#839496",
                sidebar_bg="#00212b", sidebar_icon="#586e75", sidebar_text="#839496",
                sidebar_sel_bg="#001a22", sidebar_sel_icon="#268bd2", sidebar_sel_text="#268bd2",
                state_icon="#2aa198",
                error="#dc322f", success="#859900", warning="#b58900", info="#268bd2",
                divider="#0a3541",
                table_row="#073642", table_row_alt="#0a4150",
                input_bg="#0a3541", input_text="#839496",
                mdc_surface="#073642", mat_bg="#002b36", mat_bg2="#073642",
                badge_bg="#073642", badge_text="#839496",
                badge_red="#dc322f", badge_green="#859900", badge_blue="#268bd2",
                badge_yellow="#b58900", badge_grey="#586e75",
            ),
            # Solarized Light (offizielle Light-Variante)
            light=_dark_vars(
                primary="#268bd2", accent="#b58900",
                bg="#fdf6e3", bg2="#eee8d5", card="#fdf6e3",
                text="#657b83", text2="#93a1a1",
                header_bg="#eee8d5", header_text="#657b83",
                sidebar_bg="#eee8d5", sidebar_icon="#93a1a1", sidebar_text="#657b83",
                sidebar_sel_bg="#e0d9c8", sidebar_sel_icon="#268bd2", sidebar_sel_text="#268bd2",
                state_icon="#2aa198",
                error="#dc322f", success="#859900", warning="#b58900", info="#268bd2",
                divider="#d9d0b8",
                table_row="#fdf6e3", table_row_alt="#f5eed8",
                input_bg="#eee8d5", input_text="#657b83",
                mdc_surface="#fdf6e3", mat_bg="#fdf6e3", mat_bg2="#eee8d5",
                badge_bg="#fdf6e3", badge_text="#657b83",
                badge_red="#dc322f", badge_green="#859900", badge_blue="#268bd2",
                badge_yellow="#b58900", badge_grey="#93a1a1",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "github_dark": {
        "display_name": "GitHub Dark",
        "variables": _vars(
            shared=_SHARED_GITHUB,
            dark=_dark_vars(
                primary="#58a6ff", accent="#1f6feb",
                bg="#0d1117", bg2="#161b22", card="#161b22",
                text="#c9d1d9", text2="#8b949e",
                header_bg="#161b22", header_text="#c9d1d9",
                sidebar_bg="#010409", sidebar_icon="#8b949e", sidebar_text="#c9d1d9",
                sidebar_sel_bg="#0d1117", sidebar_sel_icon="#58a6ff", sidebar_sel_text="#58a6ff",
                state_icon="#58a6ff",
                error="#f85149", success="#3fb950", warning="#d29922", info="#58a6ff",
                divider="#21262d",
                table_row="#161b22", table_row_alt="#1c2128",
                input_bg="#0d1117", input_text="#c9d1d9",
                mdc_surface="#161b22", mat_bg="#0d1117", mat_bg2="#161b22",
                badge_bg="#161b22", badge_text="#c9d1d9",
                badge_red="#f85149", badge_green="#3fb950", badge_blue="#58a6ff",
                badge_yellow="#d29922", badge_grey="#8b949e",
            ),
            # GitHub Light
            light=_dark_vars(
                primary="#0969da", accent="#1a7f37",
                bg="#ffffff", bg2="#f6f8fa", card="#ffffff",
                text="#24292f", text2="#57606a",
                header_bg="#24292f", header_text="#ffffff",
                sidebar_bg="#f6f8fa", sidebar_icon="#57606a", sidebar_text="#24292f",
                sidebar_sel_bg="#eaeef2", sidebar_sel_icon="#0969da", sidebar_sel_text="#0969da",
                state_icon="#0969da",
                error="#cf222e", success="#1a7f37", warning="#9a6700", info="#0969da",
                divider="#d0d7de",
                table_row="#ffffff", table_row_alt="#f6f8fa",
                input_bg="#f6f8fa", input_text="#24292f",
                mdc_surface="#ffffff", mat_bg="#ffffff", mat_bg2="#f6f8fa",
                badge_bg="#ffffff", badge_text="#24292f",
                badge_red="#cf222e", badge_green="#1a7f37", badge_blue="#0969da",
                badge_yellow="#9a6700", badge_grey="#57606a",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "nord": {
        "display_name": "Nord",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#88c0d0", accent="#81a1c1",
                bg="#2e3440", bg2="#3b4252", card="#3b4252",
                text="#d8dee9", text2="#81a1c1",
                header_bg="#242933", header_text="#d8dee9",
                sidebar_bg="#242933", sidebar_icon="#81a1c1", sidebar_text="#d8dee9",
                sidebar_sel_bg="#1c2028", sidebar_sel_icon="#88c0d0", sidebar_sel_text="#88c0d0",
                state_icon="#8fbcbb",
                error="#bf616a", success="#a3be8c", warning="#ebcb8b", info="#81a1c1",
                divider="#3b4252",
                table_row="#3b4252", table_row_alt="#434c5e",
                input_bg="#434c5e", input_text="#d8dee9",
                mdc_surface="#3b4252", mat_bg="#2e3440", mat_bg2="#3b4252",
                badge_bg="#3b4252", badge_text="#d8dee9",
                badge_red="#bf616a", badge_green="#a3be8c", badge_blue="#81a1c1",
                badge_yellow="#ebcb8b", badge_grey="#4c566a",
            ),
            # Nord Snowstorm (Light)
            light=_dark_vars(
                primary="#5e81ac", accent="#81a1c1",
                bg="#eceff4", bg2="#e5e9f0", card="#eceff4",
                text="#2e3440", text2="#4c566a",
                header_bg="#3b4252", header_text="#eceff4",
                sidebar_bg="#e5e9f0", sidebar_icon="#4c566a", sidebar_text="#2e3440",
                sidebar_sel_bg="#d8dee9", sidebar_sel_icon="#5e81ac", sidebar_sel_text="#5e81ac",
                state_icon="#5e81ac",
                error="#bf616a", success="#a3be8c", warning="#ebcb8b", info="#5e81ac",
                divider="#d8dee9",
                table_row="#eceff4", table_row_alt="#e5e9f0",
                input_bg="#e5e9f0", input_text="#2e3440",
                mdc_surface="#eceff4", mat_bg="#eceff4", mat_bg2="#e5e9f0",
                badge_bg="#eceff4", badge_text="#2e3440",
                badge_red="#bf616a", badge_green="#a3be8c", badge_blue="#5e81ac",
                badge_yellow="#ebcb8b", badge_grey="#4c566a",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "monokai": {
        "display_name": "Monokai",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#a6e22e", accent="#f92672",
                bg="#272822", bg2="#3e3d32", card="#3e3d32",
                text="#f8f8f2", text2="#75715e",
                header_bg="#1e1f1c", header_text="#f8f8f2",
                sidebar_bg="#1e1f1c", sidebar_icon="#75715e", sidebar_text="#f8f8f2",
                sidebar_sel_bg="#151613", sidebar_sel_icon="#a6e22e", sidebar_sel_text="#a6e22e",
                state_icon="#fd971f",
                error="#f92672", success="#a6e22e", warning="#fd971f", info="#66d9ef",
                divider="#49483e",
                table_row="#3e3d32", table_row_alt="#49483e",
                input_bg="#49483e", input_text="#f8f8f2",
                mdc_surface="#3e3d32", mat_bg="#272822", mat_bg2="#3e3d32",
                badge_bg="#3e3d32", badge_text="#f8f8f2",
                badge_red="#f92672", badge_green="#a6e22e", badge_blue="#66d9ef",
                badge_yellow="#e6db74", badge_grey="#75715e",
            ),
            # Monokai Light
            light=_dark_vars(
                primary="#272822", accent="#f92672",
                bg="#fafafa", bg2="#f5f5f5", card="#ffffff",
                text="#272822", text2="#75715e",
                header_bg="#272822", header_text="#f8f8f2",
                sidebar_bg="#f0f0f0", sidebar_icon="#75715e", sidebar_text="#272822",
                sidebar_sel_bg="#e8e8e8", sidebar_sel_icon="#a6e22e", sidebar_sel_text="#272822",
                state_icon="#fd971f",
                error="#f92672", success="#a6e22e", warning="#fd971f", info="#66d9ef",
                divider="#e0e0e0",
                table_row="#ffffff", table_row_alt="#f5f5f5",
                input_bg="#f0f0f0", input_text="#272822",
                mdc_surface="#ffffff", mat_bg="#fafafa", mat_bg2="#f5f5f5",
                badge_bg="#ffffff", badge_text="#272822",
                badge_red="#f92672", badge_green="#a6e22e", badge_blue="#66d9ef",
                badge_yellow="#e6db74", badge_grey="#75715e",
            ),
        ),
    },
    # ------------------------------------------------------------------
    "oceanic_dark": {
        "display_name": "Oceanic Dark",
        "variables": _vars(
            shared=_SHARED_PLAIN,
            dark=_dark_vars(
                primary="#00bcd4", accent="#009688",
                bg="#0a1929", bg2="#0d2137", card="#0d2137",
                text="#b0bec5", text2="#546e7a",
                header_bg="#06111c", header_text="#b0bec5",
                sidebar_bg="#06111c", sidebar_icon="#546e7a", sidebar_text="#b0bec5",
                sidebar_sel_bg="#030d14", sidebar_sel_icon="#00bcd4", sidebar_sel_text="#00bcd4",
                state_icon="#00bcd4",
                error="#ef5350", success="#66bb6a", warning="#ffa726", info="#42a5f5",
                divider="#1a3a52",
                table_row="#0d2137", table_row_alt="#102942",
                input_bg="#1a3a52", input_text="#b0bec5",
                mdc_surface="#0d2137", mat_bg="#0a1929", mat_bg2="#0d2137",
                badge_bg="#0d2137", badge_text="#b0bec5",
                badge_red="#ef5350", badge_green="#66bb6a", badge_blue="#42a5f5",
                badge_yellow="#ffa726", badge_grey="#546e7a",
            ),
            # Oceanic Light
            light=_dark_vars(
                primary="#00796b", accent="#0097a7",
                bg="#e0f2f1", bg2="#b2dfdb", card="#ffffff",
                text="#263238", text2="#546e7a",
                header_bg="#00796b", header_text="#ffffff",
                sidebar_bg="#b2dfdb", sidebar_icon="#546e7a", sidebar_text="#263238",
                sidebar_sel_bg="#a0d0cd", sidebar_sel_icon="#00796b", sidebar_sel_text="#00796b",
                state_icon="#00796b",
                error="#e53935", success="#43a047", warning="#fb8c00", info="#039be5",
                divider="#80cbc4",
                table_row="#ffffff", table_row_alt="#e0f2f1",
                input_bg="#e0f2f1", input_text="#263238",
                mdc_surface="#ffffff", mat_bg="#e0f2f1", mat_bg2="#b2dfdb",
                badge_bg="#ffffff", badge_text="#263238",
                badge_red="#e53935", badge_green="#43a047", badge_blue="#039be5",
                badge_yellow="#fb8c00", badge_grey="#546e7a",
            ),
        ),
    },
    # ------------------------------------------------------------------
    # Vom User beigetragenes Theme
    # ------------------------------------------------------------------
    "ha_homedashboard": {
        "display_name": "HA HomeDashboard",
        "variables": {
            # Card-Mod (benötigt die card-mod Custom Component)
            "card-mod-theme": "HA_homedashboard",
            "card-mod-root": (
                ":host {\n"
                "  --data-table-background-color: #283245 !important;\n"
                "  --mdc-data-table-row-fill-color: #283245 !important;\n"
                "  --mdc-data-table-row-hover-fill-color: #303d52 !important;\n"
                "}\n"
            ),
            "card-mod-card": (
                "ha-card {\n"
                "  border: none;\n"
                "  box-shadow: rgba(0, 0, 0, 0.4) 0px 2px 4px,"
                " rgba(0, 0, 0, 0.3) 0px 7px 13px -3px,"
                " rgba(0, 0, 0, 0.2) 0px -3px 0px inset;\n"
                "}\n"
            ),
            "card-mod-sidebar": (
                "paper-icon-item[role=option], paper-icon-item[aria-role=option],"
                " ha-md-list-item {\n"
                "  background: rgb(32 41 58) !important;\n"
                "}\n"
                "ha-md-list-item {\n"
                "  background: #20293a !important;\n"
                "}\n"
            ),
            # Solide Hintergrundfarbe (gilt für beide Modi als Basis)
            "card-background-color": "#181e2a",
            "mdc-theme-surface": "#181e2a",
            "md-sys-color-surface-container": "#181e2a",
            # Transparente Karten-Hintergrundfarbe
            "ha-card-background": "rgba(22,22,22, 0.3)",
            "ha-card-background-color": "rgba(22,22,22, 0.3)",
            "modes": {
                "dark": {
                    "primary-color": "#ffe084",
                    "accent-color": "steelblue",
                    "primary-text-color": "#e1e1e1",
                    "secondary-text-color": "#7a7a7a",
                    "primary-background-color": "#20293a",
                    "data-table-background-color": "#283245",
                    "card-background-color": "#181e2a",
                    "ha-card-background": "rgba(22,22,22, 0.3)",
                    "mdc-theme-surface": "#181e2a",
                    "md-menu-container-color": "#181e2a",
                    "mdc-menu-surface-fill-color": "#181e2a",
                    "text-primary-color": "#767676",
                    "text-accent-color": "#ffffff",
                    "header-text-color": "#919398",
                    "app-header-text-color": "#919398",
                    "app-header-background-color": "#181e2a",
                    "ha-label-badge-color": "#2d506e",
                    "label-badge-red": "#2d506e",
                    "ha-heading-card-title-color": "#ffe084",
                    "ha-heading-card-title-font-size": "18px",
                    "ha-heading-card-title-letter-spacing": ".5px",
                    "ha-card-border-radius": "8px 8px 35px 8px",
                    "md-dialog-container-color": "#181e2a",
                    "md-sys-color-surface": "#181e2a",
                    "md-list-container-color": "#20293a",
                    "name-font-size": "1.1rem",
                    "ha-control-select-color": "#ffe084",
                    "state-climate-auto-color": "#ffe084",
                    "material-background-color": "#181e2a",
                    "sidebar-icon-color": "var(--icon-primary-color)",
                    "sidebar-text-color": "#c9c9c9",
                    "sidebar-menu-button-background-color": "#181e2a69",
                    "sidebar-background-color": "#181e2a",
                    "sidebar-selected-background-color": "var(--primary-background-color)",
                    "sidebar-selected-icon-color": "var(--light-primary-color)",
                    "sidebar-selected-text-color": "var(--primary-color)",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Glass – Glassmorphismus mit halbtransparenten Karten & Blur
    # ------------------------------------------------------------------
    "glass": {
        "display_name": "Glass",
        "variables": {
            # card-mod aktiviert backdrop-filter blur (benötigt Card-Mod)
            "card-mod-card": (
                "ha-card {\n"
                "  backdrop-filter: blur(12px);\n"
                "  -webkit-backdrop-filter: blur(12px);\n"
                "}\n"
            ),
            "ha-card-border-radius": "20px",
            "ha-card-border-width": "1px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "primary-color": "#a78bfa",
                    "accent-color": "#38bdf8",
                    "primary-background-color": "#0f1117",
                    "secondary-background-color": "#13151c",
                    "card-background-color": "rgba(255, 255, 255, 0.05)",
                    "ha-card-background": "rgba(255, 255, 255, 0.05)",
                    "ha-card-border-color": "rgba(255, 255, 255, 0.12)",
                    "ha-card-box-shadow": "0 8px 32px 0 rgba(31, 38, 135, 0.4)",
                    "primary-text-color": "#e2e8f0",
                    "secondary-text-color": "#94a3b8",
                    "disabled-text-color": "#475569",
                    "text-primary-color": "#e2e8f0",
                    "app-header-background-color": "rgba(15, 17, 23, 0.8)",
                    "app-header-text-color": "#e2e8f0",
                    "sidebar-background-color": "rgba(13, 15, 20, 0.9)",
                    "sidebar-icon-color": "#94a3b8",
                    "sidebar-text-color": "#e2e8f0",
                    "sidebar-selected-background-color": "rgba(167, 139, 250, 0.15)",
                    "sidebar-selected-icon-color": "#a78bfa",
                    "sidebar-selected-text-color": "#a78bfa",
                    "state-icon-color": "#a78bfa",
                    "error-color": "#f87171",
                    "success-color": "#4ade80",
                    "warning-color": "#fb923c",
                    "info-color": "#38bdf8",
                    "divider-color": "rgba(255, 255, 255, 0.08)",
                    "table-row-background-color": "rgba(255, 255, 255, 0.03)",
                    "table-row-alternative-background-color": "rgba(255, 255, 255, 0.06)",
                    "input-fill-color": "rgba(255, 255, 255, 0.07)",
                    "input-background-color": "rgba(255, 255, 255, 0.07)",
                    "input-ink-color": "#e2e8f0",
                    "mdc-theme-surface": "rgba(255, 255, 255, 0.05)",
                    "material-background-color": "#0f1117",
                    "material-secondary-background-color": "#13151c",
                    "label-badge-background-color": "rgba(255, 255, 255, 0.1)",
                    "label-badge-text-color": "#e2e8f0",
                    "label-badge-red": "#f87171",
                    "label-badge-green": "#4ade80",
                    "label-badge-blue": "#38bdf8",
                    "label-badge-yellow": "#fbbf24",
                    "label-badge-grey": "#94a3b8",
                },
                "light": {
                    "primary-color": "#6d28d9",
                    "accent-color": "#0284c7",
                    "primary-background-color": "#dce8f8",
                    "secondary-background-color": "#e8f0fb",
                    "card-background-color": "rgba(255, 255, 255, 0.55)",
                    "ha-card-background": "rgba(255, 255, 255, 0.55)",
                    "ha-card-border-color": "rgba(255, 255, 255, 0.8)",
                    "ha-card-box-shadow": "0 8px 32px 0 rgba(100, 116, 139, 0.15)",
                    "primary-text-color": "#1e293b",
                    "secondary-text-color": "#64748b",
                    "disabled-text-color": "#94a3b8",
                    "text-primary-color": "#1e293b",
                    "app-header-background-color": "rgba(220, 232, 248, 0.85)",
                    "app-header-text-color": "#1e293b",
                    "sidebar-background-color": "rgba(220, 232, 248, 0.9)",
                    "sidebar-icon-color": "#64748b",
                    "sidebar-text-color": "#1e293b",
                    "sidebar-selected-background-color": "rgba(109, 40, 217, 0.1)",
                    "sidebar-selected-icon-color": "#6d28d9",
                    "sidebar-selected-text-color": "#6d28d9",
                    "state-icon-color": "#6d28d9",
                    "error-color": "#dc2626",
                    "success-color": "#16a34a",
                    "warning-color": "#d97706",
                    "info-color": "#0284c7",
                    "divider-color": "rgba(148, 163, 184, 0.3)",
                    "table-row-background-color": "rgba(255, 255, 255, 0.5)",
                    "table-row-alternative-background-color": "rgba(220, 232, 248, 0.6)",
                    "input-fill-color": "rgba(255, 255, 255, 0.7)",
                    "input-background-color": "rgba(255, 255, 255, 0.7)",
                    "input-ink-color": "#1e293b",
                    "mdc-theme-surface": "rgba(255, 255, 255, 0.55)",
                    "material-background-color": "#dce8f8",
                    "material-secondary-background-color": "#e8f0fb",
                    "label-badge-background-color": "rgba(255, 255, 255, 0.7)",
                    "label-badge-text-color": "#1e293b",
                    "label-badge-red": "#dc2626",
                    "label-badge-green": "#16a34a",
                    "label-badge-blue": "#0284c7",
                    "label-badge-yellow": "#d97706",
                    "label-badge-grey": "#94a3b8",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Sharp – geradliniges Design ohne Border-Radius
    # ------------------------------------------------------------------
    "sharp": {
        "display_name": "Sharp",
        "variables": {
            "ha-card-border-radius": "0px",
            "ha-card-border-width": "1px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "primary-color": "#3b82f6",
                    "accent-color": "#f97316",
                    "primary-background-color": "#080808",
                    "secondary-background-color": "#111111",
                    "card-background-color": "#141414",
                    "ha-card-background": "#141414",
                    "ha-card-border-color": "#2a2a2a",
                    "primary-text-color": "#f0f0f0",
                    "secondary-text-color": "#888888",
                    "disabled-text-color": "#444444",
                    "text-primary-color": "#f0f0f0",
                    "app-header-background-color": "#000000",
                    "app-header-text-color": "#f0f0f0",
                    "sidebar-background-color": "#080808",
                    "sidebar-icon-color": "#666666",
                    "sidebar-text-color": "#f0f0f0",
                    "sidebar-selected-background-color": "#1a1a1a",
                    "sidebar-selected-icon-color": "#3b82f6",
                    "sidebar-selected-text-color": "#3b82f6",
                    "state-icon-color": "#3b82f6",
                    "error-color": "#ef4444",
                    "success-color": "#22c55e",
                    "warning-color": "#f97316",
                    "info-color": "#3b82f6",
                    "divider-color": "#222222",
                    "table-row-background-color": "#111111",
                    "table-row-alternative-background-color": "#161616",
                    "input-fill-color": "#111111",
                    "input-background-color": "#111111",
                    "input-ink-color": "#f0f0f0",
                    "mdc-theme-surface": "#141414",
                    "material-background-color": "#080808",
                    "material-secondary-background-color": "#111111",
                    "label-badge-background-color": "#141414",
                    "label-badge-text-color": "#f0f0f0",
                    "label-badge-red": "#ef4444",
                    "label-badge-green": "#22c55e",
                    "label-badge-blue": "#3b82f6",
                    "label-badge-yellow": "#f97316",
                    "label-badge-grey": "#666666",
                },
                "light": {
                    "primary-color": "#2563eb",
                    "accent-color": "#ea580c",
                    "primary-background-color": "#f9fafb",
                    "secondary-background-color": "#f3f4f6",
                    "card-background-color": "#ffffff",
                    "ha-card-background": "#ffffff",
                    "ha-card-border-color": "#e5e7eb",
                    "primary-text-color": "#111827",
                    "secondary-text-color": "#6b7280",
                    "disabled-text-color": "#9ca3af",
                    "text-primary-color": "#111827",
                    "app-header-background-color": "#1f2937",
                    "app-header-text-color": "#f9fafb",
                    "sidebar-background-color": "#f3f4f6",
                    "sidebar-icon-color": "#6b7280",
                    "sidebar-text-color": "#111827",
                    "sidebar-selected-background-color": "#e5e7eb",
                    "sidebar-selected-icon-color": "#2563eb",
                    "sidebar-selected-text-color": "#2563eb",
                    "state-icon-color": "#2563eb",
                    "error-color": "#dc2626",
                    "success-color": "#16a34a",
                    "warning-color": "#d97706",
                    "info-color": "#2563eb",
                    "divider-color": "#e5e7eb",
                    "table-row-background-color": "#ffffff",
                    "table-row-alternative-background-color": "#f9fafb",
                    "input-fill-color": "#f9fafb",
                    "input-background-color": "#f9fafb",
                    "input-ink-color": "#111827",
                    "mdc-theme-surface": "#ffffff",
                    "material-background-color": "#f9fafb",
                    "material-secondary-background-color": "#f3f4f6",
                    "label-badge-background-color": "#ffffff",
                    "label-badge-text-color": "#111827",
                    "label-badge-red": "#dc2626",
                    "label-badge-green": "#16a34a",
                    "label-badge-blue": "#2563eb",
                    "label-badge-yellow": "#d97706",
                    "label-badge-grey": "#9ca3af",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Aurora – Radial-Gradient dunkelblau → waldgrün (Nordlichter)
    # ------------------------------------------------------------------
    "aurora": {
        "display_name": "Aurora",
        "variables": {
            # card-mod aktiviert backdrop-filter blur (benötigt Card-Mod)
            "card-mod-card": (
                "ha-card {\n"
                "  backdrop-filter: blur(8px);\n"
                "  -webkit-backdrop-filter: blur(8px);\n"
                "}\n"
            ),
            "ha-card-border-radius": "16px",
            "ha-card-border-width": "1px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "lovelace-background": (
                        "radial-gradient(ellipse at 80% 10%,"
                        " #0a2840 0%, #0d3d28 45%, #051a12 80%, #03090d 100%)"
                    ),
                    "primary-color": "#34d399",
                    "accent-color": "#38bdf8",
                    "primary-background-color": "#040e0a",
                    "secondary-background-color": "#071a12",
                    "card-background-color": "rgba(5, 20, 15, 0.65)",
                    "ha-card-background": "rgba(5, 20, 15, 0.65)",
                    "ha-card-border-color": "rgba(52, 211, 153, 0.18)",
                    "ha-card-box-shadow": "0 4px 24px rgba(5, 50, 30, 0.5)",
                    "primary-text-color": "#d1fae5",
                    "secondary-text-color": "#6ee7b7",
                    "disabled-text-color": "#065f46",
                    "text-primary-color": "#d1fae5",
                    "app-header-background-color": "rgba(4, 14, 10, 0.9)",
                    "app-header-text-color": "#d1fae5",
                    "sidebar-background-color": "#040e0a",
                    "sidebar-icon-color": "#059669",
                    "sidebar-text-color": "#d1fae5",
                    "sidebar-selected-background-color": "rgba(5, 150, 105, 0.2)",
                    "sidebar-selected-icon-color": "#34d399",
                    "sidebar-selected-text-color": "#34d399",
                    "state-icon-color": "#34d399",
                    "error-color": "#f87171",
                    "success-color": "#34d399",
                    "warning-color": "#fbbf24",
                    "info-color": "#38bdf8",
                    "divider-color": "rgba(52, 211, 153, 0.12)",
                    "table-row-background-color": "rgba(5, 20, 15, 0.6)",
                    "table-row-alternative-background-color": "rgba(7, 26, 18, 0.6)",
                    "input-fill-color": "rgba(255, 255, 255, 0.05)",
                    "input-background-color": "rgba(255, 255, 255, 0.05)",
                    "input-ink-color": "#d1fae5",
                    "mdc-theme-surface": "rgba(5, 20, 15, 0.8)",
                    "material-background-color": "#040e0a",
                    "material-secondary-background-color": "#071a12",
                    "label-badge-background-color": "rgba(5, 150, 105, 0.3)",
                    "label-badge-text-color": "#d1fae5",
                    "label-badge-red": "#f87171",
                    "label-badge-green": "#34d399",
                    "label-badge-blue": "#38bdf8",
                    "label-badge-yellow": "#fbbf24",
                    "label-badge-grey": "#6ee7b7",
                },
                "light": {
                    "lovelace-background": (
                        "radial-gradient(ellipse at 80% 10%,"
                        " #dbeafe 0%, #a7f3d0 55%, #d1fae5 100%)"
                    ),
                    "primary-color": "#047857",
                    "accent-color": "#1d4ed8",
                    "primary-background-color": "#ecfdf5",
                    "secondary-background-color": "#d1fae5",
                    "card-background-color": "rgba(255, 255, 255, 0.8)",
                    "ha-card-background": "rgba(255, 255, 255, 0.8)",
                    "ha-card-border-color": "rgba(4, 120, 87, 0.18)",
                    "ha-card-box-shadow": "0 4px 24px rgba(4, 120, 87, 0.08)",
                    "primary-text-color": "#064e3b",
                    "secondary-text-color": "#047857",
                    "disabled-text-color": "#6ee7b7",
                    "text-primary-color": "#064e3b",
                    "app-header-background-color": "rgba(236, 253, 245, 0.9)",
                    "app-header-text-color": "#064e3b",
                    "sidebar-background-color": "#d1fae5",
                    "sidebar-icon-color": "#047857",
                    "sidebar-text-color": "#064e3b",
                    "sidebar-selected-background-color": "rgba(4, 120, 87, 0.12)",
                    "sidebar-selected-icon-color": "#047857",
                    "sidebar-selected-text-color": "#047857",
                    "state-icon-color": "#047857",
                    "error-color": "#dc2626",
                    "success-color": "#047857",
                    "warning-color": "#d97706",
                    "info-color": "#1d4ed8",
                    "divider-color": "rgba(4, 120, 87, 0.18)",
                    "table-row-background-color": "rgba(255, 255, 255, 0.8)",
                    "table-row-alternative-background-color": "rgba(236, 253, 245, 0.8)",
                    "input-fill-color": "rgba(255, 255, 255, 0.85)",
                    "input-background-color": "rgba(255, 255, 255, 0.85)",
                    "input-ink-color": "#064e3b",
                    "mdc-theme-surface": "rgba(255, 255, 255, 0.8)",
                    "material-background-color": "#ecfdf5",
                    "material-secondary-background-color": "#d1fae5",
                    "label-badge-background-color": "rgba(255, 255, 255, 0.8)",
                    "label-badge-text-color": "#064e3b",
                    "label-badge-red": "#dc2626",
                    "label-badge-green": "#047857",
                    "label-badge-blue": "#1d4ed8",
                    "label-badge-yellow": "#d97706",
                    "label-badge-grey": "#059669",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Horizon – Linearer Gradient dunkelblau → warm-orange (Sonnenuntergang)
    # ------------------------------------------------------------------
    "horizon": {
        "display_name": "Horizon",
        "variables": {
            # card-mod aktiviert backdrop-filter blur (benötigt Card-Mod)
            "card-mod-card": (
                "ha-card {\n"
                "  backdrop-filter: blur(8px);\n"
                "  -webkit-backdrop-filter: blur(8px);\n"
                "}\n"
            ),
            "ha-card-border-radius": "12px",
            "ha-card-border-width": "1px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "lovelace-background": (
                        "linear-gradient(to bottom,"
                        " #040d1a 0%, #0a1e3d 35%, #1a3a6e 58%, #5c2800 82%, #1a0900 100%)"
                    ),
                    "primary-color": "#f59e0b",
                    "accent-color": "#38bdf8",
                    "primary-background-color": "#060d18",
                    "secondary-background-color": "#0a1629",
                    "card-background-color": "rgba(6, 18, 35, 0.7)",
                    "ha-card-background": "rgba(6, 18, 35, 0.7)",
                    "ha-card-border-color": "rgba(245, 158, 11, 0.18)",
                    "ha-card-box-shadow": "0 4px 24px rgba(10, 30, 61, 0.5)",
                    "primary-text-color": "#fef3c7",
                    "secondary-text-color": "#fbbf24",
                    "disabled-text-color": "#92400e",
                    "text-primary-color": "#fef3c7",
                    "app-header-background-color": "rgba(4, 9, 18, 0.9)",
                    "app-header-text-color": "#fef3c7",
                    "sidebar-background-color": "#060d18",
                    "sidebar-icon-color": "#b45309",
                    "sidebar-text-color": "#fef3c7",
                    "sidebar-selected-background-color": "rgba(180, 83, 9, 0.2)",
                    "sidebar-selected-icon-color": "#f59e0b",
                    "sidebar-selected-text-color": "#f59e0b",
                    "state-icon-color": "#f59e0b",
                    "error-color": "#f87171",
                    "success-color": "#34d399",
                    "warning-color": "#f59e0b",
                    "info-color": "#38bdf8",
                    "divider-color": "rgba(245, 158, 11, 0.15)",
                    "table-row-background-color": "rgba(6, 18, 35, 0.6)",
                    "table-row-alternative-background-color": "rgba(10, 22, 41, 0.6)",
                    "input-fill-color": "rgba(255, 255, 255, 0.05)",
                    "input-background-color": "rgba(255, 255, 255, 0.05)",
                    "input-ink-color": "#fef3c7",
                    "mdc-theme-surface": "rgba(6, 18, 35, 0.8)",
                    "material-background-color": "#060d18",
                    "material-secondary-background-color": "#0a1629",
                    "label-badge-background-color": "rgba(180, 83, 9, 0.3)",
                    "label-badge-text-color": "#fef3c7",
                    "label-badge-red": "#f87171",
                    "label-badge-green": "#34d399",
                    "label-badge-blue": "#38bdf8",
                    "label-badge-yellow": "#f59e0b",
                    "label-badge-grey": "#fbbf24",
                },
                "light": {
                    "lovelace-background": (
                        "linear-gradient(to bottom,"
                        " #bfdbfe 0%, #fde68a 60%, #fed7aa 100%)"
                    ),
                    "primary-color": "#c2410c",
                    "accent-color": "#1e40af",
                    "primary-background-color": "#fff7ed",
                    "secondary-background-color": "#ffedd5",
                    "card-background-color": "rgba(255, 255, 255, 0.85)",
                    "ha-card-background": "rgba(255, 255, 255, 0.85)",
                    "ha-card-border-color": "rgba(194, 65, 12, 0.15)",
                    "ha-card-box-shadow": "0 4px 24px rgba(194, 65, 12, 0.06)",
                    "primary-text-color": "#431407",
                    "secondary-text-color": "#c2410c",
                    "disabled-text-color": "#fdba74",
                    "text-primary-color": "#431407",
                    "app-header-background-color": "rgba(255, 247, 237, 0.9)",
                    "app-header-text-color": "#431407",
                    "sidebar-background-color": "#ffedd5",
                    "sidebar-icon-color": "#c2410c",
                    "sidebar-text-color": "#431407",
                    "sidebar-selected-background-color": "rgba(194, 65, 12, 0.1)",
                    "sidebar-selected-icon-color": "#c2410c",
                    "sidebar-selected-text-color": "#c2410c",
                    "state-icon-color": "#c2410c",
                    "error-color": "#dc2626",
                    "success-color": "#059669",
                    "warning-color": "#d97706",
                    "info-color": "#1e40af",
                    "divider-color": "rgba(194, 65, 12, 0.15)",
                    "table-row-background-color": "rgba(255, 255, 255, 0.85)",
                    "table-row-alternative-background-color": "rgba(255, 247, 237, 0.85)",
                    "input-fill-color": "rgba(255, 255, 255, 0.9)",
                    "input-background-color": "rgba(255, 255, 255, 0.9)",
                    "input-ink-color": "#431407",
                    "mdc-theme-surface": "rgba(255, 255, 255, 0.85)",
                    "material-background-color": "#fff7ed",
                    "material-secondary-background-color": "#ffedd5",
                    "label-badge-background-color": "rgba(255, 255, 255, 0.85)",
                    "label-badge-text-color": "#431407",
                    "label-badge-red": "#dc2626",
                    "label-badge-green": "#059669",
                    "label-badge-blue": "#1e40af",
                    "label-badge-yellow": "#d97706",
                    "label-badge-grey": "#c2410c",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Mono – Monospace-Schrift, Terminal-Ästhetik (grün auf schwarz)
    # ------------------------------------------------------------------
    "mono": {
        "display_name": "Mono",
        "variables": {
            # Monospace-Font über card-mod breit gesetzt (benötigt Card-Mod)
            "card-mod-root": (
                ":host {\n"
                "  --mdc-typography-font-family:"
                " 'SF Mono', Consolas, 'Cascadia Code', 'Courier New', monospace !important;\n"
                "  font-family:"
                " 'SF Mono', Consolas, 'Cascadia Code', 'Courier New', monospace !important;\n"
                "}\n"
            ),
            "mdc-typography-font-family": (
                "'SF Mono', Consolas, 'Cascadia Code', 'Courier New', monospace"
            ),
            "ha-card-border-radius": "4px",
            "ha-card-border-width": "1px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "primary-color": "#22c55e",
                    "accent-color": "#06b6d4",
                    "primary-background-color": "#0a0f0a",
                    "secondary-background-color": "#0f150f",
                    "card-background-color": "#0d120d",
                    "ha-card-background": "#0d120d",
                    "ha-card-border-color": "#1a2e1a",
                    "primary-text-color": "#d4f0d4",
                    "secondary-text-color": "#4ade80",
                    "disabled-text-color": "#166534",
                    "text-primary-color": "#d4f0d4",
                    "app-header-background-color": "#050a05",
                    "app-header-text-color": "#22c55e",
                    "sidebar-background-color": "#050a05",
                    "sidebar-icon-color": "#16a34a",
                    "sidebar-text-color": "#86efac",
                    "sidebar-selected-background-color": "#0d1a0d",
                    "sidebar-selected-icon-color": "#22c55e",
                    "sidebar-selected-text-color": "#22c55e",
                    "state-icon-color": "#22c55e",
                    "error-color": "#ff5555",
                    "success-color": "#22c55e",
                    "warning-color": "#ffff55",
                    "info-color": "#55ffff",
                    "divider-color": "#1a2e1a",
                    "table-row-background-color": "#0d120d",
                    "table-row-alternative-background-color": "#0f150f",
                    "input-fill-color": "#0d120d",
                    "input-background-color": "#0d120d",
                    "input-ink-color": "#d4f0d4",
                    "mdc-theme-surface": "#0d120d",
                    "material-background-color": "#0a0f0a",
                    "material-secondary-background-color": "#0f150f",
                    "label-badge-background-color": "#0d1a0d",
                    "label-badge-text-color": "#d4f0d4",
                    "label-badge-red": "#ff5555",
                    "label-badge-green": "#22c55e",
                    "label-badge-blue": "#55aaff",
                    "label-badge-yellow": "#ffff55",
                    "label-badge-grey": "#4ade80",
                },
                "light": {
                    "primary-color": "#15803d",
                    "accent-color": "#0e7490",
                    "primary-background-color": "#f0fdf4",
                    "secondary-background-color": "#dcfce7",
                    "card-background-color": "#ffffff",
                    "ha-card-background": "#ffffff",
                    "ha-card-border-color": "#bbf7d0",
                    "primary-text-color": "#052e16",
                    "secondary-text-color": "#166534",
                    "disabled-text-color": "#86efac",
                    "text-primary-color": "#052e16",
                    "app-header-background-color": "#052e16",
                    "app-header-text-color": "#d4f0d4",
                    "sidebar-background-color": "#f0fdf4",
                    "sidebar-icon-color": "#15803d",
                    "sidebar-text-color": "#052e16",
                    "sidebar-selected-background-color": "#dcfce7",
                    "sidebar-selected-icon-color": "#15803d",
                    "sidebar-selected-text-color": "#15803d",
                    "state-icon-color": "#15803d",
                    "error-color": "#dc2626",
                    "success-color": "#15803d",
                    "warning-color": "#a16207",
                    "info-color": "#0e7490",
                    "divider-color": "#bbf7d0",
                    "table-row-background-color": "#ffffff",
                    "table-row-alternative-background-color": "#f0fdf4",
                    "input-fill-color": "#f0fdf4",
                    "input-background-color": "#f0fdf4",
                    "input-ink-color": "#052e16",
                    "mdc-theme-surface": "#ffffff",
                    "material-background-color": "#f0fdf4",
                    "material-secondary-background-color": "#dcfce7",
                    "label-badge-background-color": "#dcfce7",
                    "label-badge-text-color": "#052e16",
                    "label-badge-red": "#dc2626",
                    "label-badge-green": "#15803d",
                    "label-badge-blue": "#0e7490",
                    "label-badge-yellow": "#a16207",
                    "label-badge-grey": "#4ade80",
                },
            },
        },
    },
    # ------------------------------------------------------------------
    # Rounded – Weiche Rundungen, ui-rounded Font (toll auf Apple-Geräten)
    # ------------------------------------------------------------------
    "rounded": {
        "display_name": "Rounded",
        "variables": {
            # Rounded Font über card-mod (benötigt Card-Mod)
            "card-mod-root": (
                ":host {\n"
                "  --mdc-typography-font-family:"
                " ui-rounded, 'SF Pro Rounded', 'Nunito', 'Varela Round',"
                " system-ui, sans-serif !important;\n"
                "  font-family:"
                " ui-rounded, 'SF Pro Rounded', 'Nunito', 'Varela Round',"
                " system-ui, sans-serif !important;\n"
                "}\n"
            ),
            "mdc-typography-font-family": (
                "ui-rounded, 'SF Pro Rounded', 'Nunito', 'Varela Round', system-ui, sans-serif"
            ),
            "ha-card-border-radius": "24px",
            "ha-card-border-width": "0px",
            "sidebar-menu-button-background-color": "transparent",
            "modes": {
                "dark": {
                    "primary-color": "#f9a8d4",
                    "accent-color": "#86efac",
                    "primary-background-color": "#1e1b2e",
                    "secondary-background-color": "#252238",
                    "card-background-color": "#252238",
                    "ha-card-background": "#252238",
                    "ha-card-border-color": "rgba(249, 168, 212, 0.15)",
                    "ha-card-box-shadow": "0 4px 20px rgba(0, 0, 0, 0.4)",
                    "primary-text-color": "#fde8f0",
                    "secondary-text-color": "#c4b5fd",
                    "disabled-text-color": "#6d28d9",
                    "text-primary-color": "#fde8f0",
                    "app-header-background-color": "#16131f",
                    "app-header-text-color": "#fde8f0",
                    "sidebar-background-color": "#16131f",
                    "sidebar-icon-color": "#a78bfa",
                    "sidebar-text-color": "#fde8f0",
                    "sidebar-selected-background-color": "rgba(249, 168, 212, 0.1)",
                    "sidebar-selected-icon-color": "#f9a8d4",
                    "sidebar-selected-text-color": "#f9a8d4",
                    "state-icon-color": "#f9a8d4",
                    "error-color": "#fca5a5",
                    "success-color": "#86efac",
                    "warning-color": "#fed7aa",
                    "info-color": "#a5f3fc",
                    "divider-color": "rgba(196, 181, 253, 0.15)",
                    "table-row-background-color": "#252238",
                    "table-row-alternative-background-color": "#2a2640",
                    "input-fill-color": "#2a2640",
                    "input-background-color": "#2a2640",
                    "input-ink-color": "#fde8f0",
                    "mdc-theme-surface": "#252238",
                    "material-background-color": "#1e1b2e",
                    "material-secondary-background-color": "#252238",
                    "label-badge-background-color": "rgba(249, 168, 212, 0.15)",
                    "label-badge-text-color": "#fde8f0",
                    "label-badge-red": "#fca5a5",
                    "label-badge-green": "#86efac",
                    "label-badge-blue": "#93c5fd",
                    "label-badge-yellow": "#fde68a",
                    "label-badge-grey": "#c4b5fd",
                },
                "light": {
                    "primary-color": "#db2777",
                    "accent-color": "#059669",
                    "primary-background-color": "#fdf4ff",
                    "secondary-background-color": "#fae8ff",
                    "card-background-color": "#ffffff",
                    "ha-card-background": "#ffffff",
                    "ha-card-border-color": "rgba(219, 39, 119, 0.12)",
                    "ha-card-box-shadow": "0 2px 16px rgba(219, 39, 119, 0.08)",
                    "primary-text-color": "#500724",
                    "secondary-text-color": "#9d174d",
                    "disabled-text-color": "#fba4c0",
                    "text-primary-color": "#500724",
                    "app-header-background-color": "#fdf4ff",
                    "app-header-text-color": "#500724",
                    "sidebar-background-color": "#fae8ff",
                    "sidebar-icon-color": "#9d174d",
                    "sidebar-text-color": "#500724",
                    "sidebar-selected-background-color": "rgba(219, 39, 119, 0.1)",
                    "sidebar-selected-icon-color": "#db2777",
                    "sidebar-selected-text-color": "#db2777",
                    "state-icon-color": "#db2777",
                    "error-color": "#e11d48",
                    "success-color": "#059669",
                    "warning-color": "#d97706",
                    "info-color": "#0284c7",
                    "divider-color": "rgba(219, 39, 119, 0.15)",
                    "table-row-background-color": "#ffffff",
                    "table-row-alternative-background-color": "#fdf4ff",
                    "input-fill-color": "#fdf4ff",
                    "input-background-color": "#fdf4ff",
                    "input-ink-color": "#500724",
                    "mdc-theme-surface": "#ffffff",
                    "material-background-color": "#fdf4ff",
                    "material-secondary-background-color": "#fae8ff",
                    "label-badge-background-color": "rgba(219, 39, 119, 0.1)",
                    "label-badge-text-color": "#500724",
                    "label-badge-red": "#e11d48",
                    "label-badge-green": "#059669",
                    "label-badge-blue": "#0284c7",
                    "label-badge-yellow": "#d97706",
                    "label-badge-grey": "#9d174d",
                },
            },
        },
    },
}
